# Generated by Django 5.0.1 on 2024-03-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_alter_area_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area_asignada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nomina.area'),
        ),
    ]
