# Generated by Django 5.0.1 on 2024-03-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_alter_empleado_area_asignada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area_asignada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomina.area'),
        ),
    ]
