# Generated by Django 5.0.1 on 2024-01-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
    ]
