# Generated by Django 5.0.1 on 2024-03-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_empleado_sueldo_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=0, max_digits=100)),
                ('empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('empleados_operadores', models.ManyToManyField(to='nomina.empleado')),
            ],
        ),
    ]
